TOP=..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

PROD_HOST += getNoBlock
getNoBlock_SRCS += getNoBlock.cpp
getNoBlock_LIBS += pvaClient pvAccess nt pvData ca Com

PROD_HOST += putNoBlock
putNoBlock_SRCS += putNoBlock.cpp
putNoBlock_LIBS += pvaClient pvAccess nt pvData ca Com

PROD_HOST += monitorNoBlock
monitorNoBlock_SRCS += monitorNoBlock.cpp
monitorNoBlock_LIBS += pvaClient pvAccess nt pvData ca Com


PROD_HOST += examplePvaClientProcess
examplePvaClientProcess_SRCS += examplePvaClientProcess.cpp
examplePvaClientProcess_LIBS += pvaClient pvAccess pvData ca Com


PROD_HOST += examplePvaClientGet
examplePvaClientGet_SRCS += examplePvaClientGet.cpp
examplePvaClientGet_LIBS += pvaClient pvAccess pvData ca Com

PROD_HOST += examplePvaClientPut
examplePvaClientPut_SRCS += examplePvaClientPut.cpp
examplePvaClientPut_LIBS += pvaClient pvAccess pvData ca Com


PROD_HOST += examplePvaClientMonitor
examplePvaClientMonitor_SRCS += examplePvaClientMonitor.cpp
examplePvaClientMonitor_LIBS += pvaClient pvAccess pvData ca Com


PROD_HOST += examplePvaClientMultiDouble
examplePvaClientMultiDouble_SRCS += examplePvaClientMultiDouble.cpp
examplePvaClientMultiDouble_LIBS += pvaClient pvAccess nt pvData ca Com


PROD_HOST += examplePvaClientNTMulti
examplePvaClientNTMulti_SRCS += examplePvaClientNTMulti.cpp
examplePvaClientNTMulti_LIBS += pvaClient pvAccess nt pvData ca Com


PROD_HOST += helloWorldRPC
helloWorldRPC_SRCS += helloWorldRPC.cpp
helloWorldRPC_LIBS += pvaClient pvAccess nt pvData ca Com


PROD_HOST += helloWorldPutGet
helloWorldPutGet_SRCS += helloWorldPutGet.cpp
helloWorldPutGet_LIBS += pvaClient pvAccess nt pvData ca Com



PROD_HOST += putUnion
putUnion_SRCS += putUnion.cpp
putUnion_LIBS += pvaClient pvAccess nt pvData ca Com


#===========================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

