#!/bin/bash

./controlSigned
./scalarAlarmSigned
./controlUnsigned
./scalarAlarmUnsigned
./configProcessRecord PVRsupportProcessRecord add PVRsupportDouble
./configProcessRecord PVRsupportProcessRecord add PVRsupportUByte
