#!/bin/bash
if [ $# -ne 1 ]; then
    echo "recordName?"
    read recordName
else 
    recordName=$1
fi

active=true
lowAlarmLimit=0
lowWarningLimit=0
highWarningLimit=0
highAlarmLimit=0
hysteresis=0

value=" scalarAlarm="
value+="{\"active\":\""
value+=$active
value+="\",\"lowAlarmLimit\":\""
value+=$lowAlarmLimit
value+="\",\"lowWarningLimit\":\""
value+=$lowWarningLimit
value+="\",\"highWarningLimit\":\""
value+=$highWarningLimit
value+="\",\"highAlarmLimit\":\""
value+=$highAlarmLimit
value+="\",\"hysteresis\":\""
value+=$hysteresis
value+="\"}"

pvput -r "record[process=false]field(scalarAlarm)" $recordName $value




