#!/bin/bash

if [ $# -ne 3 ]; then
    echo "recordName"
    read recordName
    echo "command?"
    read com
    echo "name"
    read name
else
    recordName=$1
    cmd=$2
    name=$3
fi

value=" argument="
value+="{\"command\":\""
value+=$cmd
value+="\",\"recordName\":\""
value+=$name
value+="\"}"

pvput -r "field(argument,result)" $recordName $value




