#!/bin/bash

./controlSigned
./scalarAlarmSigned
./controlUnsigned
./scalarAlarmUnsigned
./configProcessRecord PVRprocessRecord add PVRsupportDouble
./configProcessRecord PVRprocessRecord add PVRsupportUByte
