TOP=..

include $(TOP)/configure/CONFIG


powerSupplySRC = $(TOP)/src

INC += pv/powerSupply.h

include $(powerSupplySRC)/code/Makefile

# shared library ABI version.
SHRLIB_VERSION ?= 1.0


include $(TOP)/configure/RULES

