#!/bin/sh
source ./setEnv
echo PVRdouble       should work
${TESTCLIENT}/testGetDouble PVRdouble
echo PVRlong       should work
${TESTCLIENT}/testGetDouble PVRlong
echo PVRstring       should not work
${TESTCLIENT}/testGetDouble PVRstring
