#!/bin/sh
source ./setEnv
echo PVRbooleanArray       should work
${TESTCLIENT}/testPutStringArray PVRbooleanArray 'false,true,false'
echo PVRbyteArray       should work
${TESTCLIENT}/testPutStringArray PVRbyteArray  '1,2,3'
echo PVRshortArray       should work
${TESTCLIENT}/testPutStringArray PVRshortArray  '1,2,3'
echo PVRintArray       should work
${TESTCLIENT}/testPutStringArray PVRintArray  '1,2,3'
echo PVRlongArray       should work
${TESTCLIENT}/testPutStringArray PVRlongArray  '1,2,3'
echo PVRubyteArray       should work
${TESTCLIENT}/testPutStringArray PVRubyteArray  '1,2,3'
echo PVRushortArray       should work
${TESTCLIENT}/testPutStringArray PVRushortArray  '1,2,3'
echo PVRuintArray       should work
${TESTCLIENT}/testPutStringArray PVRuintArray  '1,2,3'
echo PVRulongArray       should work
${TESTCLIENT}/testPutStringArray PVRulongArray  '1,2,3'
echo PVRfloatArray       should work
${TESTCLIENT}/testPutStringArray PVRfloatArray '1.0,2.2,3.4'
echo PVRdoubleArray       should work
${TESTCLIENT}/testPutStringArray PVRdoubleArray '1.0,2.2,3.4'
echo PVRstringArray       should work
${TESTCLIENT}/testPutStringArray PVRstringArray 'a a,bbb,c c'
