#!/bin/sh
source ./setEnv
echo PVRdoubleArray      should work
${TESTCLIENT}/testGetDoubleArray PVRdoubleArray
echo PVRlongArray       should not work
${TESTCLIENT}/testGetDoubleArray PVRlongArray
echo PVRstringArray       should not work
${TESTCLIENT}/testGetDoubleArray PVRstringArray
