#!/bin/sh
source ./setEnv
echo PVRdoubleArray       should work
${TESTCLIENT}/testPutStringArray PVRdoubleArray '1.0,2.0,3.0'
echo PVRlongArray       should work
${TESTCLIENT}/testPutStringArray PVRlongArray  '1,2,3'
echo PVRstringArray       should work
${TESTCLIENT}/testPutStringArray PVRstringArray 'a a,bbb,c c'
