#!/bin/sh
source ./setEnv
echo PVRboolean       should not work
${TESTCLIENT}/testPutDouble PVRboolean true
echo PVRbyte       should work
${TESTCLIENT}/testPutDouble PVRbyte 127
echo PVRshort       should work
${TESTCLIENT}/testPutDouble PVRshort 32767
echo PVRint       should work
${TESTCLIENT}/testPutDouble PVRint 100000
echo PVRlong       should work
${TESTCLIENT}/testPutDouble PVRlong 100000000000
echo PVRubyte       should work
${TESTCLIENT}/testPutDouble PVRubyte 255
echo PVRushort       should work
${TESTCLIENT}/testPutDouble PVRushort 65535
echo PVRuint       should work
${TESTCLIENT}/testPutDouble PVRuint 10000
echo PVRulong       should work
${TESTCLIENT}/testPutDouble PVRulong 10000000
echo PVRfloat       should work
${TESTCLIENT}/testPutDouble PVRfloat 1.0
echo PVRdouble       should work
${TESTCLIENT}/testPutDouble PVRdouble 1.235
echo PVRstring       should not work
${TESTCLIENT}/testPutDouble PVRstring 1
echo PVRdumbPowerSupply       should work
${TESTCLIENT}/testPutDouble -r power.value PVRdumbPowerSupply 10.0
