TOP=..

include $(TOP)/configure/CONFIG

helloPutGetSRC = $(TOP)/src

INC += pv/helloPutGet.h

include $(helloPutGetSRC)/code/Makefile

# shared library ABI version.
SHRLIB_VERSION ?= 1.0


include $(TOP)/configure/RULES


