SRC_DIRS += $(EXAMPLEDATABASESRC)/code

DBD += exampleDatabaseRegister.dbd

LIBSRCS += exampleHello.cpp
LIBSRCS += exampleHelloRPC.cpp
LIBSRCS += exampleDatabase.cpp
LIBSRCS += exampleDatabaseRegister.cpp


PROD_HOST += exampleDatabaseMain
exampleDatabaseMain_SRCS += exampleDatabaseMain.cpp
exampleDatabaseMain_LIBS += exampleDatabase
exampleDatabaseMain_LIBS += pvDatabase
exampleDatabaseMain_LIBS += pvAccess
exampleDatabaseMain_LIBS += pvData
exampleDatabaseMain_LIBS += nt
exampleDatabaseMain_LIBS += Com

