#!/bin/bash

./controlSigned
./scalarAlarmSigned
./controlUnsigned
./scalarAlarmUnsigned
./configProcessRecord PVRprocessRecord add PVRcontrolDouble
./configProcessRecord PVRprocessRecord add PVRcontrolUbyte
